<template><div class="mgr"><h2>📝 合同管理</h2><el-button type="primary" size="small" @click="showForm=true;editing=false;reset()">+ 新建合同</el-button><el-table :data="list" stripe size="small" style="margin-top:12px"><el-table-column prop="contract_no" label="合同号" width="120"/><el-table-column prop="title" label="名称" min-width="160"/><el-table-column label="金额"><template #default="{row}">¥{{ row.amount?.toLocaleString() }}</template></el-table-column><el-table-column prop="start_date" label="开始" width="100"/><el-table-column prop="end_date" label="结束" width="100"/><el-table-column label="状态" width="80"><template #default="{row}"><el-tag :type="row.status==='已签署'?'success':'warning'" size="small">{{ row.status }}</el-tag></template></el-table-column><el-table-column label="操作" width="120"><template #default="{row}"><el-button size="small" @click="signContract(row)" v-if="row.status!=='已签署'">签章</el-button></template></el-table-column></el-table>
<el-dialog v-model="showForm" title="新建合同" width="420px"><el-form label-width="80px"><el-form-item label="名称"><el-input v-model="f.title"/></el-form-item><el-form-item label="金额"><el-input-number v-model="f.amount" :min="0" style="width:100%"/></el-form-item><el-form-item label="开始"><el-input v-model="f.startDate" type="date"/></el-form-item><el-form-item label="结束"><el-input v-model="f.endDate" type="date"/></el-form-item></el-form><template #footer><el-button @click="showForm=false">取消</el-button><el-button type="primary" @click="save">保存</el-button></template></el-dialog></div></template>
<script setup>import {ref,reactive,onMounted} from 'vue';import request from '@/utils/request';import {ElMessage} from 'element-plus';
const list=ref([]);const showForm=ref(false);const f=reactive({title:'',amount:0,startDate:'',endDate:''});
function reset(){Object.assign(f,{title:'',amount:0,startDate:'',endDate:''})}
async function fetch(){try{list.value=await request.get('/contracts')||[]}catch{}}
async function save(){try{await request.post('/contracts',f);showForm.value=false;fetch();ElMessage.success('已创建')}catch{}}
async function signContract(row){try{await request.put('/contracts/'+row.id,{...row,status:'已签署',changeLog:'模拟电子签章'});fetch();ElMessage.success('已签署')}catch{}}
onMounted(fetch)</script>
<style scoped>.mgr{padding:0}</style>
